name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
  - title: '🧹 Chores'
    labels:
      - 'chore'
  - title: '🔧 Refactors'
    labels:
      - 'refactor'
  - title: '📚 Documentation'
    labels:
      - 'docs'
  - title: '🔧 Git'
    labels:
      - 'git'
template: |
  ## What’s Changed

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
